### PR TITLE
[qt/i18n] Regenerate translation files

### PR DESCRIPTION
**Pull request by eumagga0x2a**
Upon [request](http://avidemux.org/smif/index.php/topic,16565.msg79189.html#msg79189), we've got a few new translatable strings lately.

### CODE REVIEW

**Comment by eumagga0x2a** [comment]
Aaaaah, damn, I think I've misunderstood the request. Please don't pull yet, I'll see if I manage to get scootergrisen's changes into the Danish translation file first.

**Comment by scootergrisen** [comment]
I made https://github.com/mean00/avidemux2/pull/82
Maybe not best way to update but what ever.

**Comment by eumagga0x2a** [comment]
Please wait just a bit, I'm on it. The changes in your pull request remove source references, this is not good.

**Comment by eumagga0x2a** [comment]
The briefly tested updated Danish translation is included now, the pull request can be merged.

**Pull request merged**
