### PR TITLE
new filter category + new filters

### PR DESCRIPTION
**Pull request by szlldm**
New filter category: Transition
Black, Fade, Fade to black moved to this category, and display names indicate as legacy.
New filter: Fade from first image
 - Similar to Fade with "from" direction
 - but with multiple effect (not just blend)

New filters: Fade in & Fade out
 - similar to Fade to black
 - but color is customizable
 - both generated from the same code base (fadeInOut)

More filters planned...

### CODE REVIEW

**Comment by eumagga0x2a** [comment]
Great, thank you, could we please delay it until after release? I would also object to deprecating fadeTo* filters as they are fast, pretty simple and do their job :-)

**Comment by szlldm** [comment]
Yes its should be after release.
The fadeTo* filters are a nightmare to set the timing, IMHO. But not deprecated, just marked as legacy :-)

**Comment by szlldm** [comment]
New filter: Fade through
Symmetric effects for scene change fading.
Multiple effect (Color blend, Saturation, Blur, Rotation, Zoom and Vignette) can be combined.

**Comment by eumagga0x2a** [comment]
> The fadeTo* filters are a nightmare to set the timing, IMHO.

I won't argue with that – the capabilities of the Avidemux UI toolkit are very limited and, without preview, one has to figure out the start and the duration in advance. I meant the implementation of the picture processing function using lookup tables, good for performance.

> But not deprecated, just marked as legacy :-)

But the subtext is the same, "don't use that".

**Comment by szlldm** [comment]
I have removed the legacy marking.
The start/end times of the fadeTo* filters are initialized to the markers.

**Comment by eumagga0x2a** [comment]
> The start/end times of the fadeTo* filters are initialized from the markers.

Awesome, would you please separate just this from the whole huge package and submit as a new pull request? I'll try to get to PC to merge it later tonight.

It would be great to disbandle this PR in digestible portions, to be evaluated after the release, each filter in its own. Adding a new category is again a separate topic, IMHO.

Thank you very much.

**Comment by szlldm** [comment]
> Awesome, would you please separate just this from the whole huge package and submit as a new pull request? I'll try to get to PC to merge it later tonight.

How about besides that, also merge the new category + category change of these filters?
The added new category is a very small change in code, but it is IMHO a significant UI change, which could be absorbed into the forthcoming release, which already will introduce many UI changes.

**Comment by eumagga0x2a** [comment]
> How about besides that, also merge the new category + category change of these filters?

OK, merging.

Regarding the new category, I am concerned that it raises hope Avidemux cannot fulfil at the present point: a proper cross-blend for both video and audio tracks.

Additionally, no matter how ridiculous this is, I am not happy with the choice of the category icon. I really hope to find a different solution.

But of course, amazing feature-rich filters, thank you very much.

PS: I would put the category at the second position (after "Transformation").

**Comment by szlldm** [comment]
> OK, merging.

There could be a communication mishaps. I actually meant, just the introduction of the new category, and the migration of existing filters + proper initialization. Not the new filters...

**Comment by eumagga0x2a** [comment]
New filters provide direct benefit to users and improve the value of the package. Not sure that a new category for existing filters would be justified.

**Comment by szlldm** [comment]
If you have a better idea for the category icon, it would be welcome, im also not fully satisfied with the current one, but it was the least bad i could find.

**Comment by eumagga0x2a** [comment]
FYI, I get a few compiler warnings where the last two probably require attention:

```
/Users/eumagga/avidemux2/avidemux_plugins/ADM_videoFilters6/fadeThrough/qt4/fadeThrough.ui: Warning: The name 'horizontalLayout_2' (QHBoxLayout) is already in use, defaulting to 'horizontalLayout_21'.
/Users/eumagga/avidemux2/avidemux_plugins/ADM_videoFilters6/fadeThrough/qt4/fadeThrough.ui: Warning: The name 'horizontalLayout_3' (QHBoxLayout) is already in use, defaulting to 'horizontalLayout_31'.
/Users/eumagga/avidemux2/avidemux_plugins/ADM_videoFilters6/fadeThrough/qt4/fadeThrough.ui: Warning: The name 'horizontalLayout_4' (QHBoxLayout) is already in use, defaulting to 'horizontalLayout_41'.
/Users/eumagga/avidemux2/avidemux_plugins/ADM_videoFilters6/fadeThrough/qt4/fadeThrough.ui: Warning: The name 'horizontalLayout_2' (QHBoxLayout) is already in use, defaulting to 'horizontalLayout_22'.
/Users/eumagga/avidemux2/avidemux_plugins/ADM_videoFilters6/fadeThrough/qt4/fadeThrough.ui: Warning: The name 'horizontalLayout_3' (QHBoxLayout) is already in use, defaulting to 'horizontalLayout_32'.
/Users/eumagga/avidemux2/avidemux_plugins/ADM_videoFilters6/fadeThrough/qt4/fadeThrough.ui: Warning: The name 'horizontalLayout_4' (QHBoxLayout) is already in use, defaulting to 'horizontalLayout_42'.
/Users/eumagga/avidemux2/avidemux_plugins/ADM_videoFilters6/fadeThrough/qt4/fadeThrough.ui: Warning: The name 'horizontalLayout_2' (QHBoxLayout) is already in use, defaulting to 'horizontalLayout_23'.
/Users/eumagga/avidemux2/avidemux_plugins/ADM_videoFilters6/fadeThrough/qt4/fadeThrough.ui: Warning: The name 'horizontalLayout_3' (QHBoxLayout) is already in use, defaulting to 'horizontalLayout_33'.
/Users/eumagga/avidemux2/avidemux_plugins/ADM_videoFilters6/fadeThrough/qt4/fadeThrough.ui: Warning: The name 'horizontalLayout_4' (QHBoxLayout) is already in use, defaulting to 'horizontalLayout_43'.
/Users/eumagga/avidemux2/avidemux_plugins/ADM_videoFilters6/fadeThrough/qt4/fadeThrough.ui: Warning: The name 'horizontalLayout_2' (QHBoxLayout) is already in use, defaulting to 'horizontalLayout_24'.
/Users/eumagga/avidemux2/avidemux_plugins/ADM_videoFilters6/fadeThrough/qt4/fadeThrough.ui: Warning: The name 'horizontalLayout_3' (QHBoxLayout) is already in use, defaulting to 'horizontalLayout_34'.
/Users/eumagga/avidemux2/avidemux_plugins/ADM_videoFilters6/fadeThrough/qt4/fadeThrough.ui: Warning: The name 'horizontalLayout_4' (QHBoxLayout) is already in use, defaulting to 'horizontalLayout_44'.
/Users/eumagga/avidemux2/avidemux_plugins/ADM_videoFilters6/fadeThrough/qt4/fadeThrough.ui: Warning: The name 'horizontalLayout_2' (QHBoxLayout) is already in use, defaulting to 'horizontalLayout_25'.
/Users/eumagga/avidemux2/avidemux_plugins/ADM_videoFilters6/fadeThrough/qt4/fadeThrough.ui: Warning: The name 'horizontalSpacer' (QSpacerItem) is already in use, defaulting to 'horizontalSpacer1'.
/Users/eumagga/avidemux2/avidemux_plugins/ADM_videoFilters6/fadeThrough/qt4/fadeThrough.ui: Warning: The name 'horizontalSpacer_2' (QSpacerItem) is already in use, defaulting to 'horizontalSpacer_21'.
/Users/eumagga/avidemux2/avidemux_plugins/ADM_videoFilters6/fadeThrough/qt4/fadeThrough.ui: Warning: The name 'horizontalLayout_3' (QHBoxLayout) is already in use, defaulting to 'horizontalLayout_35'.
/Users/eumagga/avidemux2/avidemux_plugins/ADM_videoFilters6/fadeThrough/qt4/fadeThrough.ui: Warning: The name 'horizontalLayout_4' (QHBoxLayout) is already in use, defaulting to 'horizontalLayout_45'.
/Users/eumagga/avidemux2/avidemux_plugins/ADM_videoFilters6/fadeThrough/ADM_vidFadeThrough.cpp:1009:36: warning: implicit conversion from 'double' to 'uint32_t' (aka 'unsigned int') changes
      value from 0.5 to 0 [-Wliteral-conversion]
        _param.transientVignette = 0.5;
                                 ~ ^~~
1 warning generated.
/Users/eumagga/avidemux2/avidemux_plugins/ADM_videoFilters6/fadeThrough/qt4/Q_fadeThrough.cpp:296:38: warning: implicit conversion from 'double' to 'uint32_t' (aka 'unsigned int') changes
      value from 0.5 to 0 [-Wliteral-conversion]
    myFly->param.transientVignette = 0.5;
                                   ~ ^~~
```

**Pull request merged**
