### PR TITLE
Update danish translation

### PR DESCRIPTION
**Pull request by scootergrisen**

### CODE REVIEW

**Comment by eumagga0x2a** [comment]
Thank you, but this lacks source references and is now obsoleted by [https://github.com/mean00/avidemux2/pull/81/commits/db1ff82cccf48c69eb435c1e6dc3767ef604c58f](https://github.com/mean00/avidemux2/pull/81/commits/db1ff82cccf48c69eb435c1e6dc3767ef604c58f). Source references are added by `lupdate` (`lupdate-qt5` on Fedora) called at the end of the script `qt_update_pro.sh` in the `avidemux/qt4/i18n` directory after the script was fixed on 2016-09-07 ([https://github.com/mean00/avidemux2/commit/265779eb266909c4cb7e24ec29390085f1deb8f4](https://github.com/mean00/avidemux2/commit/265779eb266909c4cb7e24ec29390085f1deb8f4)).

**Comment by scootergrisen** [comment]
Thanks that was the code i was looking for so new i can update the ts file my self it seems... even though i can't build Avidemux on Debian som easily because of dependencies problems.
I will submit a new updated translation in a while and tells see if everything is good.

**Comment by scootergrisen** [comment]
I don't know what to do what the conclicts and why there are conflicts.
What is correct way to fix this?

**Comment by eumagga0x2a** [comment]
As explained above, I had already included your translation updates in my commit added to [https://github.com/mean00/avidemux2/pull/81](https://github.com/mean00/avidemux2/pull/81), you'll have to close this pull request, unfortunately. Next time please fetch the git master and merge it into the branch you are working on first (with correctly set upstream, this amounts to

```
git fetch upstream master
git merge upstream/master
```

in your local git repository), then add your translations, commit the changes made to `avidemux/qt4/i18n/avidemux_da.ts` and push this branch to your fork on GitHub. After that you would be able to open a new pull request usually without conflicts.

We can continue [How to update translation](http://avidemux.org/smif/index.php/topic,17299.0.html) to sort out build issues (last time it was a version dependency conflict in packages hosted by the debian-multimedia repository).

**Pull request closed without merging**
