### PR TITLE
[Q_gui2] show busy cursor during navigation

### PR DESCRIPTION
**Pull request by szlldm**
give feedback during navigation

### CODE REVIEW

**Comment by eumagga0x2a** [comment]
Great, thank you.

A luxury wish: would it be possible to override cursor only if the wait exceeds some threshold? Keeping e.g. the next frame button pressed produces a lot of flicker from changing the cursor.

**Comment by szlldm** [comment]
> A luxury wish: would it be possible to override cursor only if the wait exceeds some threshold?

That was my first attempt (with QTimer::singleshot), but it does not worked. I suspect the cause is, Qt internal stuff is not updated, while ffmpeg do the magic in the background.

**Comment by eumagga0x2a** [comment]
Indeed, looks like a tough nut to crack. The slot for timeout() signal of a QTimer is not called before actionSlot() is completed.

There is more stuff I don't fully understand yet, e.g. NAVIGATION_ACTION_LOCK_THRESHOLD is almost never exceeded. With an _else_ branch added to the condition `if (actionLock<=NAVIGATION_ACTION_LOCK_THRESHOLD)`, it is almost never reached.

_busyCntr_ gets slowly incremented until it reaches NAVIGATION_ACTION_LOCK_THRESHOLD, then decremented to zero within a millisecond, resulting in cursor flickering briefly every NAVIGATION_ACTION_LOCK_THRESHOLD steps.

**Comment by szlldm** [comment]
> There is more stuff I don't fully understand yet, e.g. NAVIGATION_ACTION_LOCK_THRESHOLD is almost never exceeded. With an else branch added to the condition if (actionLock<=NAVIGATION_ACTION_LOCK_THRESHOLD), it is almost never reached.

That is interesting, because otherwise it stops piling up unserviced key events. 

Maybe the flickering could be eliminated, by adding delay _after_ busyCntr back to zero.

**Comment by eumagga0x2a** [comment]
To drain accumulating signals, we could evaluate the currently unused static admMutex singleThread in `HandleAction()` in gui_main.cpp like

```
    if(action != ACT_PlayAvi &&
       action != ACT_StopAvi &&
       action != ACT_CLOSE &&
       action != ACT_EXIT &&
       singleThread.isLocked())
    {
        ADM_info("mutex locked, returning early.\n");
        return;
    }
```
instead of solving it in Qt.

> Maybe the flickering could be eliminated, by adding delay _after_ busyCntr back to zero.

Could you please elaborate?

**Comment by szlldm** [comment]
> To drain accumulating signals, we could evaluate the currently unused static admMutex singleThread in HandleAction() in gui_main.cpp
instead of solving it in Qt.

That would be a bad idea. On the one hand the mutex is not unused, it is the sole guard that provides the in-order execution of actions; on the other this would discard every action while the sole one is serviced. The NAVIGATION_ACTION_LOCK_THRESHOLD makes possibble to queue a limited number of action (for example if i want to go forward 3 frames, and i press right arrow key three times, using the mutex it could discard 2 keypress).

>>Maybe the flickering could be eliminated, by adding delay after busyCntr back to zero.
> Could you please elaborate?

See the new commit :)

**Pull request merged**
