### PR TITLE
Updated Russian translation

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by eumagga0x2a** [comment]
Thank you for your contribution. A few notes:

- Translations marked as obsolete have no effect, it is a waste of time to correct them.
- Many English strings have keyboard accelerators, you don't provide any equivalents for cyrillic layout. Why? Keyboard accessibility is awesome.
- When translating strings containing markup (even wrong one like `&lt;b&gt;Video Decoder&lt;b&gt;` which should be fixed shortly before the .ts files get regenerated next time, it has been forgotten recently) please preserve the markup.
- When translating `   (0 track(s))` as `   (0 дорожка/-ек)`, the lenght of the string grows from 15 to 18 characters. This may result in increased width of the codec widget, pushing the right edge of the video out of sight (maybe this issue will get properly fixed later, but this is what the things look like now). I'd suggest dropping leading spaces to reduce the string length.

**Comment by TotalCaesar659** [comment]
Thank you for the very detailed answer. I'm not even software engineer, but I'll try to take all the critics into consideration.
By the way, could you tell me how to clone this commit for fixing? I know only how to clone all the git repository.

**Comment by eumagga0x2a** [comment]
I'm not a software engineer either and even new to GitHub :-) The cleanest way to handle the situation would be to save the patch locally, cancel the pull request, undo the commit e.g. by

`git push origin +1318829e3c4e2391410a1704bdb874008e75d0b6:master`

then create a new branch (e.g. `i18n-ru-updates`) followed by

`git checkout i18n-ru-updates`

apply your patch to the branch, make any corrections you like. Once you are all set, push the branch to your GitHub repository and open a new pull request from that branch. It means, never work on master, always on a branch.

**Comment by TotalCaesar659** [comment]
Thanks, but it would be better to re-create this PR. I'll close this one and pull updated translation at the next time.

**Pull request closed without merging**
