### PR TITLE
[Dxva2] lookupCodec(): after an unsuccessful mode configuration check…

### PR DESCRIPTION
**Pull request by mm1044**
…, continue checking next modes.

### CODE REVIEW

**Comment by mm1044** [comment]
(Untested...)

**Comment by mean00** [comment]
I'm not sure i'm getting the patch
What's the thing that is better with it ?

**Comment by mm1044** [comment]
For example, (as I remember on my Win.Vista)
ADM supports 3 GUIDs for H264,
assume 1st doesn't match, 2nd matchs but has no supported config, then 3rd should be tried too.

**Comment by mean00** [comment]
ok, i'll look into mergint it
Thanks

**Comment by mean00** [comment]
I"ve done it slightly differently
See latest commit

**Pull request closed without merging**
