### PR TITLE
Translation update

### PR DESCRIPTION
**Pull request by warchlak**

### CODE REVIEW

**Comment by mean00** [comment]
thank you

**Comment by mean00** [comment]
Merge is on hold  a bit, I'm waiting for Euma to check this, he's dealing with translations topics.

**Comment by eumagga0x2a** [comment]
There are multiple occurences of existing translations undone like

```
    <message>
         <location line="+23"/>
         <location filename="../../../avidemux_plugins/ADM_videoFilters6/mplayerDelogo/qt5/mpdelogo.ui" line="-17"/>
         <source>Width</source>
-        <translation>Szerokość</translation>
+        <translation type="unfinished"></translation>
     </message>
     <message>
         <location line="+20"/>
         <location filename="../../../avidemux_plugins/ADM_videoFilters6/mplayerDelogo/qt5/mpdelogo.ui" line="+7"/>
         <source>Height</source>
-        <translation>Wysokość</translation>
+        <translation type="unfinished"></translation>
     </message>
     <message>
         <location line="+20"/>
         <location filename="../../../avidemux_plugins/ADM_videoFilters6/mplayerDelogo/qt5/mpdelogo.ui" line="-14"/>
         <source>Border Width</source>
-        <translation>Szerokość obramowania</translation>
+        <translation type="unfinished"></translation>
     </message>
```

in the pull request. Are you sure this is correct?

**Comment by warchlak** [comment]
I'm still verifying parts not translated by me. So all unverified I leave as unfinished. It takes some time but finally ill do it.

**Comment by warchlak** [comment]
You can keep it on hold until you need to change these files. I will not need to create new requests.

**Comment by eumagga0x2a** [comment]
> I'm still verifying parts not translated by me. So all unverified I leave as unfinished.

No problem with marking existing translations as unfinished, but you have **removed** a lot of seemingly valid translations like those I quoted above (e.g. "Width" --> "Szerokość", "Height" --> "Wysokość" in the MPlayer Delogo plugin). Was it intentional or by accident? If translations are not completely misleading or otherwise wrong, I would suggest keeping them until they are replaced with a better alternative.

Your contributions are highly appreciated. Once this PR is merged, please don't hesitate to create new pull requests if you would like to get a patch merged.

**Comment by warchlak** [comment]
So that's what you tried to show me...
I dont delete any existing translations, so obviously it was not intended. I will look at it and figure out how to solve this in the simplest way.
Sorry for this mistake.

**Comment by warchlak** [comment]
Now everything should be ok. If i missed something, i'll add it in future updates.

**Comment by eumagga0x2a** [comment]
Great, thank you very much.

**Pull request merged**
