### PR TITLE
Greek translation 002

### PR DESCRIPTION
**Pull request by nikoss**
Update of the Greek translation 002.

Spell checking not complete, due to problems with the translation tools.

### CODE REVIEW

**Comment by eumagga0x2a** [comment]
Thank you, could you please apply the patch to the ffmpeg4x branch and resubmit the pull request? Currently only 4 hunks out of 137 fail, it should be much easier to proceed this way than to pull the PR now and to resolve merge conflicts later when ffmpeg4x gets merged back into master.

This is also necessary for the translation update to be included into the Beta release which will be done off the ffmpeg4x branch.

**Comment by nikoss** [comment]
Unfortunately, I can't... I am just the translator. Coding is not for me. I had to read your message 3 times, to "sort of" understand it (...to give you an idea).

**Comment by eumagga0x2a** [comment]
No coding is required, I'll help you. First of all, run

git checkout ffmpeg4x
git pull

in your local clone of the avidemux2 repository, then create a new branch e.g. "greek-translation-for-ffmpeg4x"

git branch greek-translation-for-ffmpeg4x
git checkout greek-translation-for-ffmpeg4x

apply the patch https://github.com/eumagga0x2a/avidemux2/commit/8bdcb928af1b6e20dec7dfc172bcc1be75b87e71.patch

patch -p1 < Path/To/8bdcb928af1b6e20dec7dfc172bcc1be75b87e71.patch

This patch is the applicable part of your translation update.

Below is the part which doesn't apply automatically (it doesn't mean that every translation has to be modified, just if a single translation in a portion of a patch called "hunk" doesn't apply, the entire hunk gets rejected):

```
--- avidemux/qt4/i18n/avidemux_el.ts
+++ avidemux/qt4/i18n/avidemux_el.ts
@@ -2792,37 +2792,37 @@ Do you want to load it  ?
     <message>
         <location line="-36"/>
         <source>Cannot find a demuxer for %s</source>
-        <translation>Αδυναμία εύρεσης αποπολυπλέκτη για το %s</translation>
+        <translation>Αδυναμία εύρεσης πολυαποπλέκτη για το %s</translation>
     </message>
     <message>
         <location line="+58"/>
         <source>width</source>
-        <translation type="unfinished"></translation>
+        <translation>πλάτος</translation>
     </message>
     <message>
         <location line="+6"/>
         <source>%sheight</source>
-        <translation type="unfinished"></translation>
+        <translation>%sύψος</translation>
     </message>
     <message>
         <location line="+1"/>
         <source> and </source>
-        <translation type="unfinished"></translation>
+        <translation> και </translation>
     </message>
     <message>
         <location line="+3"/>
         <source>%sdifferent between first and this video stream</source>
-        <translation type="unfinished"></translation>
+        <translation>%sδιαφορετικό μεταξύ της πρώτης και της παρούσας ροής βίντεου</translation>
     </message>
     <message>
         <location line="+1"/>
         <source> are </source>
-        <translation type="unfinished"></translation>
+        <translation> είναι </translation>
     </message>
     <message>
         <location line="+0"/>
         <source> is </source>
-        <translation type="unfinished"></translation>
+        <translation> είναι </translation>
     </message>
     <message>
         <location line="+2"/>
@@ -5398,7 +5404,7 @@ Drop timing informations ?</source>
     <message>
         <location line="+10"/>
         <source>© 2001 - 2018  Mean</source>
-        <translation type="unfinished"></translation>
+        <translation>© 2001 - 2018  Μυιν (Mean)</translation>
     </message>
     <message>
         <source>© 2001 - 2016  Mean</source>
@@ -7868,51 +7894,72 @@ Installation mismatch</source>
     <message>
         <location filename="../../../avidemux_plugins/ADM_videoFilters6_openGl/glShaderLoader/shader.cpp" line="+246"/>
         <source>Cannot compile shader</source>
-        <translation type="unfinished"></translation>
+        <translation>Αδυναμία σύνθεσης των σκιάσεων</translation>
     </message>
     <message>
         <location filename="../../common/ADM_editor/src/ADM_edVideoCopy.cpp" line="+449"/>
         <source>Decode time stamp (DTS) collision affecting a keyframe at %s detected.
 Dropping a keyframe will result in severely corrupted video.
 Proceed anyway?</source>
-        <translation type="unfinished"></translation>
+        <translation>Εντοπίστηκε σύγκρουση Χρονοσφραγίδων Αποκωδικοποίησης (DTS). 
+Αυτή επιρρεάζει ένα κλειδοστιγμιότυπο στα %s .
+Η απόρριψη ενός κλειδοστιγμιότυπου θα έχει ως αποτέλεσμα 
+τη δημιουργία ένός ιδιαίτερα φθαρμένου βίντεου.
+
+Να συνεχιστεί, έτσι κι αλλιώς;</translation>
     </message>
     <message>
         <location line="+6"/>
         <source>Decode time stamp (DTS) collision affecting a frame at %s detected.
 Dropping a frame may result in some video corruption.
 Proceed anyway?</source>
-        <translation type="unfinished"></translation>
+        <translation>Εντοπίστηκε σύγκρουση Χρονοσφραγίδων Αποκωδικοποίησης (DTS). 
+Αυτή επιρρεάζει ένα στιγμιότυπο στα %s .
+Η απόρριψη ενός στιγμιότυπου ίσως να έχει ως αποτέλεσμα 
+κάποια φθορά του βίντεου.
+
+Να συνεχιστεί, έτσι κι αλλιώς;</translation>
     </message>
     <message>
         <location line="+20"/>
         <source>Do not warn again and drop frames silently while saving this video?</source>
-        <translation type="unfinished"></translation>
+        <translation>Να μην ξαναγίνει προειδοποίηση, και να παραληφθούν, σιωπηλά,τα στιγμιότυπα , κατά την αποθκευση του βίντεου;</translation>
     </message>
     <message>
         <location line="+76"/>
         <source>While saving, some video frames prior to %s had to be delayed, resulting in temporary loss of A/V sync. Would you like to continue nevertheless?</source>
-        <translation type="unfinished"></translation>
+        <translation>Κατά την αποθήκευση, κάποια στιγμιότυπα του βίντεου, 
+πριν το %s, 
+έπρεπε να οριστούν με καθυστέρηση. 
+Σαν αποτέλεσμα, υπάρχει προσωρινή απώλεια συγχρονισμού 
+μεταξύ του Ήχου και του Βίντεου. 
+
+Θα ήθελες να συνιστεί, έτσι κι αλλιώς;</translation>
     </message>
     <message>
         <location filename="../../common/ADM_toolkit/automation.cpp" line="+227"/>
         <source>Permission Error</source>
-        <translation type="unfinished"></translation>
+        <translation>Σφάλμα Δικαιωμάτων</translation>
     </message>
     <message>
         <location line="+0"/>
         <source>Cannot open script &quot;%s&quot;.</source>
-        <translation type="unfinished"></translation>
+        <translation>Αδυναμία ανοίγματος του σεναρίου
+ &quot;%s&quot; .</translation>
     </message>
     <message>
         <location line="+4"/>
         <source>File Error</source>
-        <translation type="unfinished"></translation>
+        <translation>Σφάλμα Αρχείου</translation>
     </message>
     <message>
         <location line="+0"/>
         <source>Script &quot;%s&quot; does not exist.</source>
-        <translation type="unfinished"></translation>
+        <translation variants="yes">
+            <lengthvariant>Δεν υπάρχει το σενάριο
+ &quot;%s&quot;</lengthvariant>
+            <lengthvariant></lengthvariant>
+        </translation>
     </message>
 </context>
 <context>
@@ -8384,32 +8431,32 @@ This message will not be displayed again.</source>
     <message>
         <location filename="../../../avidemux_plugins/ADM_videoFilters6/blackenBorder/qt4/blackenBorders.ui" line="+14"/>
         <source>Blacken Borders</source>
-        <translation type="unfinished"></translation>
+        <translation>Μαύρισμα των Ορίων</translation>
     </message>
     <message>
         <location line="+38"/>
         <source>Right:</source>
-        <translation type="unfinished"></translation>
+        <translation>Δεξιά:</translation>
     </message>
     <message>
         <location line="+7"/>
         <source>Top:</source>
-        <translation type="unfinished"></translation>
+        <translation>Κορυφή:</translation>
     </message>
     <message>
         <location line="+43"/>
         <source>Reset</source>
-        <translation type="unfinished"></translation>
+        <translation>Επαναφορά</translation>
     </message>
     <message>
         <location line="+21"/>
         <source>Bottom:</source>
-        <translation type="unfinished"></translation>
+        <translation>Πάτος:</translation>
     </message>
     <message>
         <location line="+7"/>
         <source>Left:</source>
-        <translation type="unfinished"></translation>
+        <translation>Αριστερά:</translation>
     </message>
 </context>
 <context>
```

Please edit the already patched file filling in translations from above, modifying these translations when necessary.

When you are ready with that, please submit a new pull request for the ffmpeg4x branch, not the master branch. This one will be closed.

**Comment by nikoss** [comment]
You developers, someday(?), have to understand, that not everyone wants to or is fit to be a developer. I know you mean well, but what you say sounds like an unknown foreign language to me. I don't even have a git clone of avidemux. These "simple steps" are hours of work for a novice person. Plus, 10 minutes after I will get finished, I will forget all the commands I just used. Totally counter productive! It's better to spend all that time doing some translation. It's ok if some messages are left untranslated. There, always, some left out.

**Comment by eumagga0x2a** [comment]
> I don't even have a git clone of avidemux.

I assumed your translation workflow would be similar to my translation workflow which turned out to be incorrect.

Okay, I'll pull it and see how far I'll get manually resolving resulting conflicts.

**Pull request merged**
