### PR TITLE
[ADM_demuxers/Matroska] reuse indexing dialog

### PR DESCRIPTION
**Pull request by szlldm**
prevent very annoying focus stealing, by reusing the same dialog for cluster and image indexing
(wondering if cluster and image indexing could be united into a single process, as after a cluster found image the images in it. this would be faster in case file located on a HDD)

also prevent memory leak (undeleted work)

### CODE REVIEW

**Comment by eumagga0x2a** [comment]
> wondering if cluster and image indexing could be united into a single process, as after a cluster found image the images in it. this would be faster in case file located on a HDD

Exactly this. Solves the issue of focus stealing at its source.

**Comment by szlldm** [comment]
So 92b9d49b76588c4812f3aaf5c06dd973594e4eff made this irrelevant? :)

**Comment by eumagga0x2a** [comment]
> So [92b9d49](https://github.com/mean00/avidemux2/commit/92b9d49b76588c4812f3aaf5c06dd973594e4eff) made this irrelevant? :)

For the purpose of preventing Avidemux window moved to a different workspace from suddenly popping up in foreground on the current one in the middle of indexing a Matroska video – yes.

**Comment by szlldm** [comment]
👍

**Pull request closed without merging**
