### PR TITLE
[videoFilter] New filter: Image stabilizer

### PR DESCRIPTION
**Pull request by szlldm**
Reduce camera shakiness.
I hope the cmake file is OK.

### CODE REVIEW

**Comment by eumagga0x2a** [comment]
I cannot count how many times this feature was requested, thank you very much.

The only thing which I noticed (apart from encapsulation issues which are probably trivial to fix, so I can do it later myself) and which whould be great to sort out right away is preview changed after "peek original" button pressed and released.

**Comment by szlldm** [comment]
I have removed the "peek original" button, because there is no simple solution for the mentioned problem. IMHO it is not a critical miss.

**Comment by szlldm** [comment]
Probably i have to take the harder route, as the same effect occurs when changing parameters :'(

**Comment by szlldm** [comment]
Done. The "peek original" button will not be returned, as internal state wouldnt be updated if the button would be pressed during a play.

**Comment by eumagga0x2a** [comment]
Thanks!

**Pull request merged**
