### PR TITLE
Updated Russian translation

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by eumagga0x2a** [comment]
This is much better, thank you. Small things like

`<translation type="unfinished">&amp;lВыбор</translation>`

can be fixed in a follow-up IMHO. You should not modify source strings though.

I haven't checked if the accelerators are conflict-free, you do have a build environment to test your changes live, don't you? Anyway, I think this all can be done in a follow-up after this pull request has been merged.

**Comment by TotalCaesar659** [comment]
@eumagga0x2a , sorry I didn't see that before merging, I went to sleep after committing.
Do you want me to compile it and test? If you do, I don't know how to do that)
But of course I'll try to fix errors, if you tell me what I have to do.

**Comment by eumagga0x2a** [comment]
@TotalCaesar659 

> Do you want me to compile it and test? If you do, I don't know how to do that

You won't regret if you invest a few hours into setting up a Linux installation (I would recommend Fedora) with build environment. I can't imagine how it is possible to work on code or translation without an ability to verify that your changes work right and don't break anything. If you wish more guidance, you're welcome to register for [http://avidemux.org/smif/index.php](http://avidemux.org/smif/index.php).

**Comment by TotalCaesar659** [comment]
Thanks, I'll try it in a few weeks when I'll have more free time.

**Pull request merged**
