### PR TITLE
[ADM_threadQueue] bugfix + exclusive access for state variable

### PR DESCRIPTION
**Pull request by szlldm**
-fix stopping issue  (half second delay) during playback (which resulted very slow navigation during play)
-always access threadState exclusively

### CODE REVIEW

**Review by mean00 — COMMENTED** [review]
Some of the new locks are not needed IMHO.
The scheme you want to avoid is read/modify/write

something like this : 
lock
threadState=running
unlock
does not help i think, unless threadstate=running is not atomic

Same for the read only/comparison only test

**Comment by szlldm** [comment]
"According to the C++11 ISO Standard, the volatile keyword is only meant for use for hardware access; do not use it for inter-thread communication."

**Comment by mean00** [comment]
Let me detail, If the variable is of simple type (i.e. int/enum) and fits in a register

foo=bar

and 

lock()
foo=bar
unlock()

are identical as far as protection are concerned
The 2nd may be much slower

**Comment by szlldm** [comment]
Quoting from the top answer at [https://stackoverflow.com/questions/2484980/why-is-volatile-not-considered-useful-in-multithreaded-c-or-c-programming](https://stackoverflow.com/questions/2484980/why-is-volatile-not-considered-useful-in-multithreaded-c-or-c-programming).
"volatile does not guarantee that no reordering takes place. Assume that we use a volatile variable as a flag to indicate whether or not some data is ready to be read. In our code, we simply set the flag after preparing the data, so all looks fine. But what if the instructions are reordered so the flag is set first?"

**Comment by szlldm** [comment]
std::atomic could be used, but that would limit to C++11 and later

**Comment by szlldm** [comment]
+1: volatile != atomic. there could be some architecture, where writing a volatile address, would lead to a read-modify-write (for example "volatile uint8_t", on some 32bit arch)

**Comment by eumagga0x2a** [comment]
Merging now. In case of substantial regressions which cannot be solved quickly I'll back out this one and #381, but test builds with both included run fine so far.

**Pull request merged**
